name: Docker image build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERTOKEN }}" | docker login -u yash140204 --password-stdin

      - name: Build & Push Image
        run: |
          set -e  # Exit on any error
          docker build -t yash140204/fastapi-app:latest .
          docker push yash140204/fastapi-app:latest

